
import React, { useState, useEffect, useRef } from 'react';
import { generatePetSummary } from '../services/geminiService';
import { DailyReport } from '../types';

interface AISummaryProps {
  report: DailyReport;
}

const AISummary: React.FC<AISummaryProps> = ({ report }) => {
  const [summary, setSummary] = useState<string>('');
  const [loading, setLoading] = useState(true);
  const prevDataRef = useRef<string>('');

  useEffect(() => {
    // 只有当核心指标发生变化时才重新请求 AI，避免无效刷新
    const currentDataKey = `${report.petId}-${report.activity.steps}-${report.vitals.avgTemp}-${report.vitals.avgPressure}`;
    if (prevDataRef.current === currentDataKey) return;
    
    const fetchSummary = async () => {
      setLoading(true);
      const text = await generatePetSummary(report);
      setSummary(text);
      setLoading(false);
      prevDataRef.current = currentDataKey;
    };
    
    fetchSummary();
  }, [report]); // 监听整个 report 对象，但在内部进行差异校验

  return (
    <div className="bg-white rounded-[2rem] p-8 shadow-sm border border-gray-100 relative overflow-hidden group">
      {/* Background Accent */}
      <div className="absolute top-0 right-0 w-32 h-32 bg-indigo-50 rounded-full -mr-16 -mt-16 transition-transform group-hover:scale-110 duration-700"></div>
      
      <div className="flex items-center gap-4 mb-6 relative z-10">
        <div className="bg-indigo-600 p-3 rounded-2xl shadow-lg shadow-indigo-100">
          <svg className={`w-6 h-6 text-white ${loading ? 'animate-spin' : ''}`} fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" />
          </svg>
        </div>
        <div>
          <h3 className="text-lg font-bold text-gray-800">AI 深度健康洞察</h3>
          <div className="flex items-center gap-2">
            <span className="flex h-2 w-2">
              <span className={`animate-ping absolute inline-flex h-2 w-2 rounded-full opacity-75 ${loading ? 'bg-indigo-400' : 'bg-green-400'}`}></span>
              <span className={`relative inline-flex rounded-full h-2 w-2 ${loading ? 'bg-indigo-500' : 'bg-green-500'}`}></span>
            </span>
            <p className="text-[10px] text-gray-400 font-bold uppercase tracking-widest">
              {loading ? '正在解析实时指标...' : '分析报告已生成'}
            </p>
          </div>
        </div>
      </div>
      
      <div className="min-h-[100px] relative z-10">
        {loading ? (
          <div className="space-y-3">
            <div className="h-4 bg-gray-100 rounded-full w-full animate-pulse"></div>
            <div className="h-4 bg-gray-100 rounded-full w-11/12 animate-pulse" style={{ animationDelay: '0.2s' }}></div>
            <div className="h-4 bg-gray-100 rounded-full w-4/5 animate-pulse" style={{ animationDelay: '0.4s' }}></div>
          </div>
        ) : (
          <div className="relative">
            <div className="absolute -left-2 top-0 text-5xl text-indigo-100 font-serif opacity-50 select-none">“</div>
            <p className="text-gray-700 leading-[1.8] font-medium pl-6 pr-2 text-[15px]">
              {summary}
            </p>
            <div className="flex justify-end mt-4">
              <span className="text-[10px] bg-indigo-50 text-indigo-500 px-3 py-1 rounded-full font-bold">
                GENERATED BY GEMINI FLASH
              </span>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default AISummary;
